import { FoodItem } from './health-data.service';

export const FOOD_DATA: Omit<FoodItem, 'mealType'>[] = [
  { name: 'Apple', calories: 95, protein: 0, carbs: 25, fat: 0, quantity: 1 },
  { name: 'Banana', calories: 105, protein: 1, carbs: 27, fat: 0, quantity: 1 },
  { name: 'Chicken Breast (100g)', calories: 165, protein: 31, carbs: 0, fat: 4, quantity: 1 },
  { name: 'Broccoli (1 cup)', calories: 55, protein: 4, carbs: 11, fat: 1, quantity: 1 },
  { name: 'Oatmeal (1 cup cooked)', calories: 150, protein: 5, carbs: 27, fat: 3, quantity: 1 },
  { name: 'Grilled Chicken Salad', calories: 350, protein: 40, carbs: 10, fat: 15, quantity: 1 },
  { name: 'Salmon (100g)', calories: 206, protein: 22, carbs: 0, fat: 13, quantity: 1 },
  { name: 'White Rice (1 cup cooked)', calories: 205, protein: 4, carbs: 45, fat: 0, quantity: 1 },
  { name: 'Tofu (100g)', calories: 94, protein: 10, carbs: 2, fat: 6, quantity: 1 },
  { name: 'Avocado', calories: 234, protein: 3, carbs: 12, fat: 22, quantity: 1 },
  { name: 'Almonds (1/4 cup)', calories: 207, protein: 8, carbs: 8, fat: 18, quantity: 1 },
  { name: 'Greek Yogurt (1 cup)', calories: 100, protein: 17, carbs: 6, fat: 0, quantity: 1 },
  { name: 'Whole Wheat Bread (1 slice)', calories: 81, protein: 4, carbs: 14, fat: 1, quantity: 1 },
  { name: 'Peanut Butter (2 tbsp)', calories: 190, protein: 7, carbs: 8, fat: 16, quantity: 1 },
  { name: 'Egg (large)', calories: 78, protein: 6, carbs: 1, fat: 5, quantity: 1 },
  { name: 'Quinoa (1 cup cooked)', calories: 222, protein: 8, carbs: 39, fat: 4, quantity: 1 },
  { name: 'Lean Beef (100g)', calories: 250, protein: 26, carbs: 0, fat: 15, quantity: 1 },
  { name: 'Sweet Potato (medium)', calories: 103, protein: 2, carbs: 24, fat: 0, quantity: 1 },
  { name: 'Spinach (1 cup)', calories: 7, protein: 1, carbs: 1, fat: 0, quantity: 1 },
  { name: 'Lentils (1 cup cooked)', calories: 230, protein: 18, carbs: 40, fat: 1, quantity: 1 },
  { name: 'Cottage Cheese (1 cup)', calories: 163, protein: 28, carbs: 6, fat: 2, quantity: 1 },
  { name: 'Dark Chocolate (1 oz)', calories: 170, protein: 2, carbs: 13, fat: 12, quantity: 1 },
  { name: 'Orange', calories: 62, protein: 1, carbs: 15, fat: 0, quantity: 1 },
  { name: 'Bell Pepper (medium)', calories: 24, protein: 1, carbs: 6, fat: 0, quantity: 1 },
  { name: 'Tuna (canned, 3 oz)', calories: 100, protein: 22, carbs: 0, fat: 1, quantity: 1 },
  { name: 'Brown Rice (1 cup cooked)', calories: 216, protein: 5, carbs: 45, fat: 2, quantity: 1 },
  { name: 'Shrimp (100g)', calories: 85, protein: 20, carbs: 0, fat: 0, quantity: 1 },
  { name: 'Walnuts (1/4 cup)', calories: 190, protein: 4, carbs: 4, fat: 18, quantity: 1 },
  { name: 'Milk (1 cup)', calories: 103, protein: 8, carbs: 12, fat: 2, quantity: 1 },
  { name: 'Edamame (1 cup shelled)', calories: 188, protein: 18, carbs: 14, fat: 8, quantity: 1 }
];
